### PR TITLE
Update near.js

### PR DESCRIPTION
**Pull request by PiVortex**

### CODE REVIEW

**Comment by gagdiez** [comment]
trying to summon @race-of-sloths

**Comment by gagdiez** [comment]
trying to summon @race-of-sloths

**Comment by gagdiez** [comment]
@race-of-sloths score: 1

**Comment by gagdiez** [comment]
@race-of-sloths unpause

**Comment by race-of-sloths** [comment]
### ⏰️ PR is already merged
It's too late to include us now. Include us before the merge next time!

**Pull request merged**
